KW_YEAR = "년"
KW_MONTH = "월"
KW_DAY = "일"
KW_LAST_YEAR = "작년"
KW_LAST_YEAR2 = "지난해"
KW_LAST_LAST_YEAR = "재작년"
KW_QUARTER = "분기"
KW_FIRST_HALF = "상반기"
KW_LAST_HALF = "하반기"
KW_THIS_YEAR = "올해"
KW_THIS_YEAR2 = "이번연도"
KW_THIS_MONTH = "이번달"
KW_LAST_MONTH = "지난달"
KW_LAST_QUARTER = "지난분기"
KW_TODAY = "오늘"
KW_TODAY2 = "금일"
KW_TODAY3 = "당일"
KW_THIS_MONTH2 = "금월"
KW_THIS_MONTH3 = "당월"
KW_LAST_MONTH2 = "전월"
KW_MONTHS_AGO = "개월전"
KW_MONTHS = "개월"
KW_YEARS = "개년"
KW_YEARS_AGO = "년전"

ABS_WORDS = [KW_YEAR, KW_MONTH, KW_DAY]

REL_WORDS = [KW_LAST_YEAR, KW_LAST_LAST_YEAR, KW_QUARTER, KW_FIRST_HALF, KW_LAST_HALF,
    KW_THIS_YEAR, KW_THIS_YEAR2, KW_THIS_MONTH, KW_LAST_YEAR2, KW_LAST_MONTH, KW_LAST_QUARTER,
    KW_TODAY, KW_TODAY2, KW_TODAY3, KW_THIS_MONTH2, KW_THIS_MONTH3, KW_LAST_MONTH2, KW_MONTHS, KW_MONTHS_AGO,
    KW_YEARS, KW_YEARS_AGO]

NUMB_WORDS = ["일", "이", "삼", "사", "오", "육", "칠", "팔", "구", "십", "백", "천"]